version: '2'
services:
    voess2-app:
        image: voess2
        external_links:
            - voess2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/voess2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    voess2-mysql:
        extends:
            file: mysql.yml
            service: voess2-mysql
