version: '2'
services:
    voess2-mysql:
        container_name: voess2-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/voess2/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=voess2
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
